const C=window.CAP_CONFIG||{},configured=C.key&&!C.key.includes('COLLE_ICI'),db=configured?supabase.createClient(C.url,C.key):null;
const euro=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}),WEEK=604800000;
const today=()=>new Date().toISOString().slice(0,10),months=(a,b)=>{a=new Date(a);b=new Date(b);return Math.max(0,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth())};
let user=null,tab='home',entries=[],flows=[];const settings={target:50000,savings:11000,targetDate:'2028-09-30',income:5500,carPayment:320,carPrincipal:28000,carRate:6.75,carStart:'2026-10-01',carPayoff:'2028-09-30'};
function car(){let n=months(settings.carStart,settings.carPayoff),r=Math.pow(1+settings.carRate/100,1/12)-1,f=Math.pow(1+r,n);return Math.max(0,settings.carPrincipal*f-settings.carPayment*((f-1)/r))}
function stats(){let real=settings.savings+entries.filter(x=>['Mise de côté','Entrée réelle'].includes(x.type)).reduce((a,x)=>a+Number(x.amount),0)-entries.filter(x=>x.type==='Retrait épargne').reduce((a,x)=>a+Number(x.amount),0),ins=flows.filter(x=>x.status!=='Réalisé'&&x.direction==='in').reduce((a,x)=>a+Number(x.amount),0),outs=flows.filter(x=>x.status!=='Réalisé'&&x.direction==='out').reduce((a,x)=>a+Number(x.amount),0),auto=car(),projected=real+ins-outs-auto,remaining=Math.max(0,settings.target-projected),weeks=Math.max(1,Math.ceil((new Date(settings.targetDate)-new Date())/WEEK));return{real,ins,outs,auto,projected,remaining,weekly:remaining/weeks,monthly:remaining/weeks*52/12}}
async function load(){let [e,f]=await Promise.all([db.from('entries').select('*').order('id',{ascending:false}),db.from('flows').select('*').order('id')]);if(e.error)throw e.error;if(f.error)throw f.error;entries=e.data||[];flows=f.data||[];render()}
async function boot(){if(!configured)return render();user=(await db.auth.getSession()).data.session?.user||null;if(user){await load();db.channel('sync').on('postgres_changes',{event:'*',schema:'public',table:'entries'},load).on('postgres_changes',{event:'*',schema:'public',table:'flows'},load).subscribe()}else render()}
function nav(){return user?['home','saisie','hypotheses','historique'].map(x=>`<button class="nav ${tab===x?'active':''}" data-tab="${x}">${x}</button>`).join(''):''}
function home(){let s=stats();return `<div class="card hero"><div class="row"><div><div>Contribution nette projetée</div><div class="big">${euro.format(s.projected)}</div></div><div><div>Cible prudente</div><div class="metric">${euro.format(settings.target)}</div><div>Reste ${euro.format(s.remaining)}</div></div></div></div><div class="grid"><div class="card"><div class="muted">Épargne mensuelle</div><div class="metric">${euro.format(s.monthly)}</div></div><div class="card"><div class="muted">Épargne hebdomadaire</div><div class="metric">${euro.format(s.weekly)}</div></div><div class="card"><div class="muted">Solde auto sept. 2028</div><div class="metric">${euro.format(s.auto)}</div></div></div><div class="card"><h2>Ressources</h2><div class="details"><div><span>Épargne actuelle</span><b>${euro.format(s.real)}</b></div><div><span>Entrées projetées</span><b>${euro.format(s.ins)}</b></div><div><span>Sorties projetées</span><b>− ${euro.format(s.outs)}</b></div><div><span>Solde crédit auto</span><b>− ${euro.format(s.auto)}</b></div></div></div>`}
function login(){return `<div class="card" style="max-width:520px;margin:40px auto"><h2>Connexion</h2><p class="muted">Entre une adresse autorisée. Tu recevras un lien de connexion.</p><form id="login" style="margin-top:15px"><input class="full" name="email" type="email" required><button class="btn green full">Recevoir le lien</button></form><p id="msg" class="notice" style="display:none;margin-top:12px"></p></div>`}
function saisie(){return `<div class="card"><h2>Nouvelle saisie</h2><form id="entry"><select name="person"><option>Antoine</option><option>Laura</option><option>Commun</option></select><select name="type"><option>Dépense</option><option>Mise de côté</option><option>Entrée réelle</option><option>Retrait épargne</option></select><input name="amount" type="number" step=".01" placeholder="Montant" required><input name="date" type="date" value="${today()}" required><input class="full" name="note" placeholder="Commentaire"><button class="btn green full">Enregistrer</button></form></div>`}
function hypotheses(){return `<div class="card"><h2>Hypothèses partagées</h2><form id="flow"><input name="label" placeholder="Libellé" required><input name="amount" type="number" placeholder="Montant" required><input name="date" type="date" value="${today()}" required><select name="direction"><option value="in">Entrée</option><option value="out">Sortie</option></select><button class="btn green full">Ajouter</button></form></div><div class="card">${flows.map(x=>`<div class="item"><div><b>${x.label}</b><div class="muted">${x.date} · ${x.status}</div></div><b>${x.direction==='in'?'+':'−'}${euro.format(x.amount)}</b><button class="red" data-df="${x.id}">Supprimer</button></div>`).join('')}</div>`}
function historique(){return `<div class="card"><h2>Historique partagé</h2>${entries.length?entries.map(x=>`<div class="item"><div><b>${x.note||x.type}</b><div class="muted">${x.person} · ${x.date} · ${x.type}</div></div><b>${euro.format(x.amount)}</b><button class="red" data-de="${x.id}">Supprimer</button></div>`).join(''):'Aucune opération'}</div>`}
function render(){document.querySelector('#nav').innerHTML=nav();document.querySelector('#app').innerHTML=!configured?`<div class="notice">Ouvre config.js et colle la Publishable key Supabase.</div>`:!user?login():({home,saisie,hypotheses,historique}[tab]());bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});let l=document.querySelector('#login');if(l)l.onsubmit=async e=>{e.preventDefault();let email=new FormData(l).get('email'),m=document.querySelector('#msg'),{error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});m.style.display='block';m.textContent=error?error.message:'Lien envoyé. Consulte ta messagerie.'};let form=document.querySelector('#entry');if(form)form.onsubmit=async e=>{e.preventDefault();let f=new FormData(form),{error}=await db.from('entries').insert({person:f.get('person'),type:f.get('type'),amount:Number(f.get('amount')),date:f.get('date'),note:f.get('note')});if(error)alert(error.message);else{tab='home';await load()}};let fl=document.querySelector('#flow');if(fl)fl.onsubmit=async e=>{e.preventDefault();let f=new FormData(fl),{error}=await db.from('flows').insert({label:f.get('label'),amount:Number(f.get('amount')),date:f.get('date'),status:'Prévu',direction:f.get('direction')});if(error)alert(error.message);else await load()};document.querySelectorAll('[data-de]').forEach(x=>x.onclick=async()=>{await db.from('entries').delete().eq('id',x.dataset.de);load()});document.querySelectorAll('[data-df]').forEach(x=>x.onclick=async()=>{await db.from('flows').delete().eq('id',x.dataset.df);load()})}
boot();